export const webSiteProjects = [
  {
    img: require("../../assets/websites/formularz.webp"),
    alt: "formularz szkolny",
    title: "Kursy szkolne",
    href: "https://www.ambitni.edu.pl/konfigurator/",
    code: "https://github.com/Rejnszu/school-form",
  },
  {
    img: require("../../assets/websites/biker.webp"),
    alt: "Biker",
    title: "Biker",
    href: "https://rejnszu.github.io/Bike-Shop-Site/",
    code: "https://github.com/Rejnszu/Bike-Shop-Site",
  },
  {
    img: require("../../assets/websites/domsi.webp"),
    alt: "Domsi",
    title: "Domsi",
    href: "https://esklep.newtool.pl/",
    code: "https://github.com/Rejnszu/Domsi",
  },
  {
    img: require("../../assets/websites/portfolio.webp"),
    alt: "Stare Portfolio",
    title: "Stare Portfolio",
    href: "https://rejnszu.pl/",
    code: "https://github.com/Rejnszu?tab=repositories",
  },
  {
    img: require("../../assets/websites/sprawdzauto.webp"),
    alt: "Sprawdzauto",
    title: "Sprawdzauto",
    href: "https://www.sprawdzauto.com.pl/",
    code: "https://github.com/Rejnszu/Sprawdzauto",
  },
  {
    img: require("../../assets/websites/rebro.webp"),
    alt: "Rebro",
    title: "Rebro",
    href: "https://rebro.pl/",
    code: "https://github.com/Rejnszu/Rebro",
  },
  {
    img: require("../../assets/websites/newtool.webp"),
    alt: "Newtool",
    title: "Newtool",
    href: "https://newtool.pl/",
    code: "https://github.com/Rejnszu/Newtool",
  },
  {
    img: require("../../assets/websites/rehasquad.webp"),
    alt: "Rehasquad",
    title: "Rehasquad",
    href: "https://rehasquad.pl/",
    code: "https://github.com/Rejnszu/Rehasquad",
  },
];

export const AppProjects = [
  {
    img: require("../../assets/apps/musify.webp"),
    alt: "Musify",
    title: "Musify",
    href: "https://rejnszu.github.io/Musify/",
    code: "https://github.com/Rejnszu/Musify",
  },
  {
    img: require("../../assets/apps/tanks.webp"),
    alt: "Tanks",
    title: "Tanks",
    href: "https://rejnszu.github.io/Tanks-game/",
    code: "https://github.com/Rejnszu/Tanks-game",
  },
  {
    img: require("../../assets/apps/tictactoe.jpg"),
    alt: "Tic Tac Toe",
    title: "Tic Tac Toe",
    href: "https://rejnszu.github.io/Tic-Tac-Toe-AI/",
    code: "https://github.com/Rejnszu/Tic-Tac-Toe-AI",
  },
  {
    img: require("../../assets/apps/crypto.webp"),
    alt: "CryptoCompare",
    title: "Crypto Compare",
    href: "https://rejnszu.github.io/React-Crypto-MarketCap-Compare/",
    code: "https://github.com/Rejnszu/React-Crypto-MarketCap-Compare",
  },
  {
    img: require("../../assets/apps/calculator.webp"),
    alt: "Calculator",
    title: "Calculator",
    href: "https://rejnszu.github.io/React-Calculator/",
    code: "https://github.com/Rejnszu/React-Calculator",
  },
  {
    img: require("../../assets/apps/fithits.webp"),
    alt: "FitHits",
    title: "FitHits",
    href: "https://rejnszu.github.io/FitHits/",
    code: "https://github.com/Rejnszu/FitHits",
  },
  {
    img: require("../../assets/apps/currency.webp"),
    alt: "Currency Exchange",
    title: "Currency Exchange",
    href: "https://rejnszu.github.io/Currency-exchange/",
    code: "https://github.com/Rejnszu/Currency-exchange",
  },
  {
    img: require("../../assets/apps/quiz.webp"),
    alt: "Quiz",
    title: "Quiz",
    href: "https://rejnszu.pl/quiz/",
    code: "https://github.com/Rejnszu/Quiz",
  },
];
