import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiBootstrap,
  SiSass,
  SiReact,
  SiRedux,
  SiWordpress,
  SiPhp,
  SiGit,
  SiTypescript,
  SiWebpack,
  SiNextdotjs,
} from "react-icons/si";

export const skills = [
  { name: "HTML", percent: "60%", icon: <SiHtml5 /> },
  { name: "CSS", percent: "70%", icon: <SiCss3 /> },
  { name: "Sass", percent: "50%", icon: <SiSass /> },
  { name: "BOOTSTRAP", percent: "50%", icon: <SiBootstrap /> },
  {
    name: "JAVASCRIPT",
    percent: "60%",
    icon: <SiJavascript />,
    additionals: ["Rest Api", "AJAX"],
  },
  {
    name: "REACT",
    percent: "65%",
    icon: <SiReact />,
    additionals: ["React Router", "Framer Motion", "Redux"],
  },
  { name: "NEXT JS", percent: "50%", icon: <SiNextdotjs /> },
  {
    name: "REDUX",
    percent: "60%",
    icon: <SiRedux />,
    additionals: ["Redux Toolkit", "RTK Query"],
  },
  { name: "TYPESCRIPT", percent: "30%", icon: <SiTypescript /> },
  { name: "WEBPACK", percent: "30%", icon: <SiWebpack /> },
  { name: "WORDPRESS", percent: "30%", icon: <SiWordpress /> },
  { name: "GIT", percent: "60%", icon: <SiGit /> },
];
